# Control your input devices
# See https://wiki.hypr.land/Configuring/Basics/Variables/#input

input {
  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 250

  # Start with numlock on by default
  numlock_by_default = true

  touchpad {
    # Two-finger clicks for right-click
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty|foot), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

# Enable touchpad gestures for changing workspaces
# See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
# gesture = 3, horizontal, workspace

# Enable touchpad gestures for moving focus
# gesture = 3, left,  dispatcher, movefocus, l
# gesture = 3, right, dispatcher, movefocus, r

source = input-specific-hardware.conf
