# Fijar workspaces 1, 2 y 3 al monitor DP-1
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
# Fijar workspaces 4, 5 y é al monitor DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
