/**
 * Permission Gate Extension
 *
 * Prompts for confirmation before running potentially dangerous bash commands.
 * The dialog shows the command plus a short description of what it does,
 * generated by a one-shot LLM call using the session's active model
 * (via ctx.modelRegistry, stateless — no subagent/session spawned). If the
 * model call fails or times out, falls back to local heuristic rules.
 *
 * Patterns checked: rm -rf, chmod/chown 777
 *
 * Note: `sudo` is not gated on its own — NOPASSWD sudo is part of the normal
 * workflow (e.g. managing the home-server over SSH).
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { Context, Message } from "@earendil-works/pi-ai";

// ---------------------------------------------------------------------------
// Fallback heuristic (used when the LLM call fails or times out)
// ---------------------------------------------------------------------------

interface Rule {
	re: RegExp;
	describe: (m: RegExpMatchArray) => string;
}

const MAX_TARGET = 60;

function truncate(s: string): string {
	return s.length > MAX_TARGET ? `${s.slice(0, MAX_TARGET - 1)}…` : s;
}

function hasFlag(args: string, short: string, long: string): boolean {
	return new RegExp(`(^|\\s)-[a-z]*${short}|--${long}`).test(args);
}

function describeSegment(segment: string): string {
	// Strip leading env assignments like FOO=bar
	const cmd = segment.trim().replace(/^[A-Za-z_][A-Za-z0-9_]*=\S*\s+/, "");

	const rules: Rule[] = [
		{
			re: /^sudo\s+(.+)$/s,
			describe: (m) => {
				const inner = describeSegment(m[1]);
				return inner ? `${inner} (con privilegios de root)` : "ejecuta un comando con privilegios de root";
			},
		},
		{
			re: /^rm\b(.*)$/s,
			describe: (m) => {
				const args = m[1];
				const target =
					truncate(args.replace(/--?\S+/g, "").replace(/^\s*--\s*/, "").trim()) || "los archivos indicados";
				const parts = [`borra ${target}`];
				if (hasFlag(args, "r", "recursive")) parts.push("recursivamente");
				if (hasFlag(args, "f", "force")) parts.push("sin pedir confirmación (irreversible)");
				return parts.join(" ");
			},
		},
		{
			re: /^chmod\b.*\b777\b/,
			describe: () => "da permisos de lectura/escritura/ejecución a todos los usuarios (777)",
		},
		{
			re: /^chown\b.*\b777\b/,
			describe: () => "cambia propietario/grupo asignando permisos totales (777)",
		},
	];

	for (const rule of rules) {
		const m = cmd.match(rule.re);
		if (m) return rule.describe(m);
	}
	return "";
}

function heuristicDescription(command: string): string {
	const segments = command
		.split(/\|\||&&|;|\|/)
		.map((s) => s.trim())
		.filter(Boolean);
	const descriptions = [...new Set(segments.map(describeSegment).filter(Boolean))];
	return descriptions.join("; ") || "ejecuta un comando potencialmente peligroso";
}

// ---------------------------------------------------------------------------
// LLM description (one-shot, stateless call with the session's active model)
// ---------------------------------------------------------------------------

const DESCRIPTION_SYSTEM =
	"Eres un asistente que explica comandos de shell a un usuario. Responde ÚNICAMENTE con una " +
	"descripción breve en español neutro: una sola frase de máximo ~15 palabras, sin comillas, " +
	"sin el comando repetido y sin preámbulos. Si el comando es destructivo, hazlo notar.";

const LLM_TIMEOUT_MS = 10_000;

async function describeWithModel(command: string, ctx: any): Promise<string | null> {
	try {
		const model = ctx.model;
		const registry = ctx.modelRegistry;
		const provider = registry?.getProvider?.(model?.provider);
		if (!model || !provider?.streamSimple) return null;

		const auth = registry?.getProviderAuth?.(model.provider) ?? {};

		const messages: Message[] = [
			{
				role: "user",
				content: `¿Qué hace este comando de shell? Responde solo con la descripción breve.\n\n${command}`,
				timestamp: Date.now(),
			},
		];
		const context: Context = { systemPrompt: DESCRIPTION_SYSTEM, messages };

		// Abort on user cancel (ctx.signal) or after a deadline so the
		// confirmation dialog never hangs on a slow model.
		const signals: AbortSignal[] = [AbortSignal.timeout(LLM_TIMEOUT_MS)];
		if (ctx.signal) signals.push(ctx.signal);
		const signal = AbortSignal.any(signals);

		const stream = provider.streamSimple(model, context, {
			apiKey: auth.apiKey,
			maxTokens: 150,
			signal,
		});

		let text = "";
		for await (const event of stream) {
			if (event.type === "text_delta") text += event.delta;
			else if (event.type === "error") return null;
		}

		text = text.trim().replace(/^["“'`]+|["”'`]+$/g, "");
		return text || null;
	} catch {
		return null;
	}
}

// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
	const dangerousPatterns = [/\brm\s+(-rf?|--recursive)/i, /\b(chmod|chown)\b.*777/i];
	const descriptionCache = new Map<string, string>();

	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "bash") return undefined;

		const command = event.input.command as string;
		const isDangerous = dangerousPatterns.some((p) => p.test(command));

		if (isDangerous) {
			if (!ctx.hasUI) {
				// In non-interactive mode, block by default
				return { block: true, reason: "Dangerous command blocked (no UI for confirmation)" };
			}

			const description =
				descriptionCache.get(command) ?? (await describeWithModel(command, ctx)) ?? heuristicDescription(command);
			if (!descriptionCache.has(command)) descriptionCache.set(command, description);

			const choice = await ctx.ui.select(
				`⚠️ Comando potencialmente peligroso\n\n  ${command}\n\n  Qué hace: ${description}\n\n¿Ejecutar?`,
				["Sí, ejecutar", "No, cancelar"],
			);

			if (choice !== "Sí, ejecutar") {
				return { block: true, reason: "Blocked by user" };
			}
		}

		return undefined;
	});
}
