/**
 * Permission Gate Extension
 *
 * Prompts for confirmation before running potentially dangerous bash commands.
 * The dialog shows the command plus a short description of what it does,
 * generated by a one-shot LLM call using the session's active model
 * (via ctx.modelRegistry, stateless — no subagent/session spawned). If the
 * model call fails or times out, falls back to local heuristic rules.
 *
 * Patterns checked: rm -rf, chmod/chown 777
 *
 * Sandbox /tmp: si TODO el alcance del comando queda dentro de /tmp (paths
 * absolutos bajo /tmp, o relativos con cwd de la sesión dentro de /tmp), no se
 * pide confirmación. Siempre piden confirmación aunque apunten a /tmp:
 *   - Intérpretes/scripts (bash /tmp/x.sh, python /tmp/x.py, sh -c, eval…):
 *     un archivo en /tmp puede hacer cualquier cosa.
 *   - Expansiones no verificables: $VAR, $(...), `...`, ~.
 *   - Comandos compuestos donde la otra parte toca paths fuera de /tmp.
 *
 * Note: `sudo` is not gated on its own — NOPASSWD sudo is part of the normal
 * workflow (e.g. managing the home-server over SSH).
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { Context, Message } from "@earendil-works/pi-ai";
import { realpathSync } from "node:fs";
import { resolve as resolvePath } from "node:path";

// ---------------------------------------------------------------------------
// Fallback heuristic (used when the LLM call fails or times out)
// ---------------------------------------------------------------------------

interface Rule {
	re: RegExp;
	describe: (m: RegExpMatchArray) => string;
}

const MAX_TARGET = 60;

function truncate(s: string): string {
	return s.length > MAX_TARGET ? `${s.slice(0, MAX_TARGET - 1)}…` : s;
}

function hasFlag(args: string, short: string, long: string): boolean {
	return new RegExp(`(^|\\s)-[a-z]*${short}|--${long}`).test(args);
}

function describeSegment(segment: string): string {
	// Strip leading env assignments like FOO=bar
	const cmd = segment.trim().replace(/^[A-Za-z_][A-Za-z0-9_]*=\S*\s+/, "");

	const rules: Rule[] = [
		{
			re: /^sudo\s+(.+)$/s,
			describe: (m) => {
				const inner = describeSegment(m[1]);
				return inner ? `${inner} (con privilegios de root)` : "ejecuta un comando con privilegios de root";
			},
		},
		{
			re: /^rm\b(.*)$/s,
			describe: (m) => {
				const args = m[1];
				const target =
					// Only strip tokens that start at a word boundary (real flags),
					// so paths like /tmp/pi-gate-test-dir keep their dashes intact.
					truncate(args.replace(/(^|\s)--?[\w-]+/g, "$1").replace(/^\s*--\s*/, "").trim()) ||
					"los archivos indicados";
				const parts = [`borra ${target}`];
				if (hasFlag(args, "r", "recursive")) parts.push("recursivamente");
				if (hasFlag(args, "f", "force")) parts.push("sin pedir confirmación (irreversible)");
				return parts.join(" ");
			},
		},
		{
			re: /^chmod\b.*\b777\b/,
			describe: () => "da permisos de lectura/escritura/ejecución a todos los usuarios (777)",
		},
		{
			re: /^chown\b.*\b777\b/,
			describe: () => "cambia propietario/grupo asignando permisos totales (777)",
		},
	];

	for (const rule of rules) {
		const m = cmd.match(rule.re);
		if (m) return rule.describe(m);
	}
	return "";
}

function heuristicDescription(command: string): string {
	const segments = command
		.split(/\|\||&&|;|\|/)
		.map((s) => s.trim())
		.filter(Boolean);
	const descriptions = [...new Set(segments.map(describeSegment).filter(Boolean))];
	return descriptions.join("; ") || "ejecuta un comando potencialmente peligroso";
}

// ---------------------------------------------------------------------------
// Sandbox /tmp: comandos con alcance íntegramente dentro de /tmp no preguntan
// ---------------------------------------------------------------------------

const TMP_ROOT = realpathSync("/tmp");

// Wrappers que no cambian el alcance del comando real que les sigue.
const TRANSPARENT_PREFIXES = new Set(["sudo", "env", "nice", "nohup", "time", "timeout", "stdbuf", "command"]);

// Ejecutan código arbitrario: aunque el archivo viva en /tmp, puede tocar
// cualquier cosa → siempre piden confirmación.
const INTERPRETER_COMMANDS = new Set([
	"bash", "sh", "ash", "dash", "zsh", "ksh", "fish",
	"eval", "exec", "source", ".",
	"python", "python3", "node", "deno", "bun", "ruby", "perl", "php", "lua",
	"xargs",
]);

// Comandos que operan sobre archivos: SUS argumentos se tratan siempre como
// posibles rutas (incluso palabras sueltas), porque pueden escribir fuera.
const FILE_COMMANDS = new Set([
	"rm", "rmdir", "mv", "cp", "ln", "mkdir", "touch", "chmod", "chown", "chgrp",
	"shred", "truncate", "install", "tee", "dd", "unlink", "mkfifo", "mknod",
	"unzip", "gunzip",
]);

function realpathSafe(p: string): string {
	try {
		return realpathSync(p);
	} catch {
		return p; // aún no existe
	}
}

function isInsideTmp(p: string): boolean {
	return p === TMP_ROOT || p.startsWith(`${TMP_ROOT}/`);
}

/** true si el token es una ruta verificable y queda dentro de /tmp. */
function isTmpPath(token: string, cwd: string | undefined): boolean {
	// Expansiones del shell (~, $VAR, $(...), `...`) y paréntesis: no verificables.
	if (token.startsWith("~") || token.includes("$") || token.includes("`") || token.includes("(")) return false;
	const resolved = token.startsWith("/") ? resolvePath(token) : cwd ? resolvePath(cwd, token) : null;
	if (!resolved) return false;
	// realpath escapa symlinks existentes (rm/chmod los cruzan o los siguen);
	// si el path no existe todavía, realpathSafe devuelve la resolución léxica.
	return isInsideTmp(realpathSafe(resolved));
}

function segmentIsTmpOnly(segment: string, cwd: string | undefined): boolean {
	// Separa redirectores pegados (2>/dev/null, >out, <in) y tokeniza.
	const tokens = segment
		.replace(/(\d+>>|&>>|>&|>|<)/g, " $1 ")
		.split(/\s+/)
		.map((t) => t.replace(/^["']+|["']+$/g, ""))
		.filter(Boolean);

	let expectCommand = true;
	let isFileCmd = false;
	let cmdWord = "";
	for (const token of tokens) {
		if (token.startsWith("#")) break; // comentario: lo que sigue no cuenta
		if (/^(\d+>>|&>>|>&|>|<)$/.test(token)) continue; // redirector
		if (/^\d+$/.test(token)) continue; // duraciones, conteos
		if (expectCommand && token.startsWith("-")) continue; // flags del wrapper (nice -n)
		// dd usa if=/of= como args: verificarlos ANTES de la regla de asignaciones.
		if (cmdWord === "dd" && /^(if|of)=/.test(token)) {
			if (!isTmpPath(token.slice(3), cwd)) return false;
			continue;
		}
		if (/^[A-Za-z_][A-Za-z0-9_]*=/.test(token)) continue; // asignaciones FOO=bar

		if (expectCommand) {
			const base = token.replace(/^\/.*\//, ""); // /usr/bin/rm -> rm
			if (TRANSPARENT_PREFIXES.has(base)) continue;
			if (INTERPRETER_COMMANDS.has(base)) return false;
			expectCommand = false;
			cmdWord = base;
			isFileCmd = FILE_COMMANDS.has(base);
			continue;
		}

		if (token.startsWith("-")) {
			// --flag=valor puede llevar una ruta en el valor.
			const eq = token.indexOf("=");
			if (eq !== -1 && !isTmpPath(token.slice(eq + 1), cwd)) return false;
			continue;
		}
		if (/^[ugoa]*[+-=][rwxXstGo]*,?$/.test(token)) continue; // modos simbólicos de chmod
		if (token.includes(":")) continue; // user:grupo de chown, URLs
		if (token === "/dev/null") continue;

		// En comandos de archivos todo argumento es candidata a ruta; en otros
		// comandos solo cuentan los tokens con forma de ruta ("echo listo" pasa).
		const looksLikePath = token.includes("/") || token === "." || token === "..";
		if ((isFileCmd || looksLikePath) && !isTmpPath(token, cwd)) return false;
	}
	return true;
}

/** true si el comando completo queda dentro del sandbox /tmp. */
export function isTmpOnly(command: string, cwd: string | undefined): boolean {
	const segments = command
		.split(/\|\||&&|;|\||\n|&/)
		.map((s) => s.trim())
		.filter(Boolean);
	if (segments.length === 0) return false;
	return segments.every((s) => segmentIsTmpOnly(s, cwd));
}

// ---------------------------------------------------------------------------
// LLM description (one-shot, stateless call with the session's active model)
// ---------------------------------------------------------------------------

const DESCRIPTION_SYSTEM =
	"Eres un asistente que explica comandos de shell a un usuario. Responde ÚNICAMENTE con una " +
	"descripción breve en español neutro: una sola frase de máximo ~15 palabras, sin comillas, " +
	"sin el comando repetido y sin preámbulos. Si el comando es destructivo, hazlo notar.";

const LLM_TIMEOUT_MS = 10_000;

let debugFs: typeof import("node:fs") | null = null;

async function debugLog(entry: Record<string, unknown>): Promise<void> {
	try {
		if (!debugFs) debugFs = await import("node:fs");
		debugFs.appendFileSync("/tmp/perm-gate-debug.log", JSON.stringify({ t: new Date().toISOString(), ...entry }) + "\n");
	} catch {}
}

async function describeWithModel(command: string, ctx: any): Promise<string | null> {
	try {
		const model = ctx.model;
		const registry = ctx.modelRegistry;
		const provider = registry?.getProvider?.(model?.provider);
		if (!model) {
			await debugLog({ llm: "fail", why: "sin ctx.model" });
			return null;
		}
		if (!provider?.streamSimple) {
			await debugLog({ llm: "fail", why: "sin provider.streamSimple", providerKeys: Object.keys(provider ?? {}) });
			return null;
		}

		const resolved = (await registry?.getProviderAuth?.(model.provider)) ?? {};
		const apiKey = resolved?.auth?.key ?? resolved?.auth?.apiKey;
		if (!apiKey) {
			await debugLog({ llm: "fail", why: "sin apiKey", resolvedKeys: Object.keys(resolved ?? {}), authKeys: Object.keys(resolved?.auth ?? {}) });
		}

		const messages: Message[] = [
			{
				role: "user",
				content: `¿Qué hace este comando de shell? Responde solo con la descripción breve.\n\n${command}`,
				timestamp: Date.now(),
			},
		];
		const context: Context = { systemPrompt: DESCRIPTION_SYSTEM, messages };

		// Abort on user cancel (ctx.signal) or after a deadline so the
		// confirmation dialog never hangs on a slow model.
		const signals: AbortSignal[] = [AbortSignal.timeout(LLM_TIMEOUT_MS)];
		if (ctx.signal) signals.push(ctx.signal);
		const signal = AbortSignal.any(signals);

		const stream = provider.streamSimple(model, context, {
			apiKey,
			maxTokens: 150,
			signal,
		});

		let text = "";
		for await (const event of stream) {
			if (event.type === "text_delta") text += event.delta;
			else if (event.type === "error") {
				await debugLog({ llm: "fail", why: "evento error", error: String((event as any).error ?? event) });
				return null;
			}
		}

		text = text.trim().replace(/^["“'`]+|["”'`]+$/g, "");
		if (!text) await debugLog({ llm: "fail", why: "respuesta vacía" });
		return text || null;
	} catch (e) {
		await debugLog({ llm: "fail", why: "excepción", error: String(e) });
		return null;
	}
}

// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
	const dangerousPatterns = [/\brm\s+(-rf?|--recursive)/i, /\b(chmod|chown)\b.*777/i];
	const descriptionCache = new Map<string, string>();

	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "bash") return undefined;

		const command = event.input.command as string;
		const isDangerous = dangerousPatterns.some((p) => p.test(command));

		if (isDangerous) {
			// Sandbox /tmp: nada cuyo alcance quede dentro de /tmp pide confirmación,
			// tampoco en modo no interactivo.
			if (isTmpOnly(command, typeof ctx.cwd === "string" ? ctx.cwd : undefined)) {
				await debugLog({ tmpSandbox: true, command });
				return undefined;
			}

			if (!ctx.hasUI) {
				// In non-interactive mode, block by default
				return { block: true, reason: "Dangerous command blocked (no UI for confirmation)" };
			}

			const cached = descriptionCache.get(command);
			let description: string;
			let fromLLM = false;
			if (cached !== undefined) {
				description = cached;
			} else {
				const llm = await describeWithModel(command, ctx);
				if (llm) {
					// Solo cacheamos aciertos del LLM: un fallo transitorio no debe
					// quedar pegado en la cache durante toda la sesión.
					description = llm;
					descriptionCache.set(command, llm);
					fromLLM = true;
				} else {
					description = heuristicDescription(command);
				}
			}

			// DEBUG temporal: registrar qué corrió
			await debugLog({ hasUI: ctx.hasUI, model: ctx.model?.id, fromLLM, cacheHit: cached !== undefined, description });

			const choice = await ctx.ui.select(
				`⚠️ Comando potencialmente peligroso\n\n  ${command}\n\n  Qué hace: ${description}\n\n¿Ejecutar?`,
				["Sí, ejecutar", "No, cancelar"],
			);

			if (choice !== "Sí, ejecutar") {
				return { block: true, reason: "Blocked by user" };
			}
		}

		return undefined;
	});
}
